import { moduleResources, moduleSrcMain } from "./gradle-common.js";
import {
  renderMavenExtraModulePoms,
  renderMavenModulePom,
  renderMavenParentPom,
  renderStandaloneMavenPom,
} from "./maven-multimodule.js";
import { packagePath, pascalCase, type PlatformRenderer } from "./types.js";
import { extraModuleSources } from "./paper.js";

/**
 * BungeeCord templates: Maven against `bungeecord-api`, `bungee.yml`
 * and the `Plugin` main class; multi-module via a Maven reactor.
 */
export const renderBungeeCord: PlatformRenderer = (context) => {
  const deps = context.versions[0]?.deps ?? {};
  const mainClass = pascalCase(context.name);
  const pkg = packagePath(context.packageName);
  const slug = packagePath(context.packageName).split("/").pop() ?? "project";
  const entryDir = moduleSrcMain(context.modules[0] ?? "main", true);
  const files = [];

  if (context.multimodule) {
    files.push({
      path: "pom.xml",
      contents: renderMavenModulePom(context, slug, context.modules[0] ?? "main", true),
    });
    files.push({ path: "pom-parent.xml", contents: renderMavenParentPom(context, slug) });
  } else {
    files.push({
      path: "pom.xml",
      contents: renderStandaloneMavenPom(
        context,
        slug,
        [
          "        <dependency>",
          "            <groupId>net.md-5</groupId>",
          "            <artifactId>bungeecord-api</artifactId>",
          `            <version>${deps.api_version ?? "1.20-R0.3-SNAPSHOT"}</version>`,
          "            <scope>provided</scope>",
          "        </dependency>",
        ],
        [
          "        <repository>",
          "            <id>sonatype-snapshots</id>",
          "            <url>https://oss.sonatype.org/content/repositories/snapshots</url>",
          "        </repository>",
        ],
      ),
    });
  }

  files.push(
    {
      path: `${moduleResources(context.modules[0] ?? "main", true)}/bungee.yml`,
      contents: [
        `name: ${context.name}`,
        `version: '${context.version}'`,
        `main: ${context.packageName}.${mainClass}`,
        "description: Generated by Devix",
        "",
      ].join("\n"),
    },
    {
      path: `${entryDir}/${pkg}/${mainClass}.java`,
      contents: [
        `package ${context.packageName};`,
        "",
        "import net.md_5.bungee.api.plugin.Plugin;",
        "",
        "/**",
        ` * Entry point of the ${context.name} proxy plugin.`,
        " */",
        `public final class ${mainClass} extends Plugin {`,
        "    @Override",
        "    public void onEnable() {",
        `        getLogger().info("${context.name} enabled");`,
        "    }",
        "}",
        "",
      ].join("\n"),
    },
    ...extraModuleSources(context, "proxy plugin"),
    ...renderMavenExtraModulePoms(context, slug),
  );
  return files;
};
