import { packagePath, pascalCase, type PlatformRenderer, type TemplateFile } from "./types.js";

/**
 * BungeeCord templates: Maven pom against bungeecord-api, a
 * `bungee.yml` descriptor and the Plugin main class.
 */
export const renderBungeeCord: PlatformRenderer = (context) => {
  const pkg = packagePath(context.packageName);
  const mainClass = pascalCase(context.name);
  const files: TemplateFile[] = [];

  files.push({
    path: "pom.xml",
    contents: [
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<project xmlns="http://maven.apache.org/POM/4.0.0"',
      '         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"',
      '         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">',
      "    <modelVersion>4.0.0</modelVersion>",
      "",
      `    <groupId>${context.packageName}</groupId>`,
      `    <artifactId>${context.name}</artifactId>`,
      `    <version>${context.version}</version>`,
      "    <packaging>jar</packaging>",
      "",
      "    <properties>",
      "        <maven.compiler.release>17</maven.compiler.release>",
      "        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>",
      "    </properties>",
      "",
      "    <repositories>",
      "        <repository>",
      "            <id>sonatype-snapshots</id>",
      "            <url>https://oss.sonatype.org/content/repositories/snapshots</url>",
      "        </repository>",
      "    </repositories>",
      "",
      "    <dependencies>",
      "        <dependency>",
      "            <groupId>net.md-5</groupId>",
      "            <artifactId>bungeecord-api</artifactId>",
      "            <version>1.20-R0.2-SNAPSHOT</version>",
      "            <scope>provided</scope>",
      "        </dependency>",
      "    </dependencies>",
      "</project>",
      "",
    ].join("\n"),
  });

  files.push({
    path: "src/main/resources/bungee.yml",
    contents: [
      `name: ${context.name}`,
      `version: '${context.version}'`,
      "main: " + `${context.packageName}.${mainClass}`,
      "description: Generated by Devix",
      "",
    ].join("\n"),
  });

  files.push({
    path: `src/main/java/${pkg}/${mainClass}.java`,
    contents: [
      `package ${context.packageName};`,
      "",
      "import net.md_5.bungee.api.plugin.Plugin;",
      "",
      "/**",
      ` * Entry point of the ${context.name} proxy plugin.`,
      " */",
      `public final class ${mainClass} extends Plugin {`,
      "    @Override",
      "    public void onEnable() {",
      `        getLogger().info("${context.name} enabled");`,
      "    }",
      "}",
      "",
    ].join("\n"),
  });

  files.push({
    path: ".gitignore",
    contents: ["target/", ".idea/", "*.iml", ""].join("\n"),
  });

  return files;
};
