import {
  extraModuleDependencies,
  gradleJavaBlocks,
  moduleResources,
  moduleSrcMain,
  renderSingleModuleSettings,
} from "./gradle-common.js";
import { renderExtraModuleBuilds, renderMultimoduleSettings } from "./gradle-multimodule.js";
import { packagePath, pascalCase, type PlatformRenderer, type TemplateFile } from "./types.js";
import { extraModuleSources } from "./paper.js";

/**
 * Folia templates: like Paper but with the classic `plugin.yml`
 * (Folia does not support the paper-plugin bootstrap model), the
 * `folia-api` line from the version catalog, regionised-threading
 * guidance in the main class and multi-module support.
 */
export const renderFolia: PlatformRenderer = (context) => {
  const deps = context.versions[0]?.deps ?? {};
  const mainClass = pascalCase(context.name);
  const pkg = packagePath(context.packageName);
  const files: TemplateFile[] = [];

  files.push({
    path: "settings.gradle",
    contents: context.multimodule
      ? renderMultimoduleSettings(context)
      : renderSingleModuleSettings(context.name, ["gradlePluginPortal()"]),
  });

  files.push({
    path: "build.gradle",
    contents: [
      "plugins {",
      "    java",
      "}",
      "",
      `version = '${context.version}'`,
      `group = '${context.packageName}'`,
      "",
      "repositories {",
      "    mavenCentral()",
      "    maven { url = 'https://repo.papermc.io/repository/maven-public/' }",
      "}",
      "",
      "dependencies {",
      '    compileOnly "dev.folia:folia-api:${project.api_version}"',
      ...extraModuleDependencies(context),
      "}",
      "",
      ...gradleJavaBlocks(context.versions[0]?.javaVersion ?? 21),
    ].join("\n"),
  });

  files.push({
    path: "gradle.properties",
    contents: [
      "org.gradle.jvmargs=-Xmx2G",
      "",
      "# Version catalog (managed by devix minecraft init --mc)",
      ...Object.entries(deps).map(([key, value]) => `${key}=${value}`),
      "",
    ].join("\n"),
  });

  files.push({
    path: `${moduleResources(context.modules[0] ?? "main", true)}/plugin.yml`,
    contents: [
      `name: ${context.name}`,
      `version: '${context.version}'`,
      `main: ${context.packageName}.${mainClass}`,
      `api-version: '${context.versions[0]?.minecraft ?? "1.21"}'`,
      "description: Generated by Devix for Folia",
      "folia-supported: true",
      "",
    ].join("\n"),
  });

  files.push({
    path: `${moduleSrcMain(context.modules[0] ?? "main", true)}/${pkg}/${mainClass}.java`,
    contents: [
      `package ${context.packageName};`,
      "",
      "import org.bukkit.plugin.java.JavaPlugin;",
      "",
      "/**",
      ` * Entry point of the ${context.name} plugin on Folia.`,
      " *",
      " * Folia splits the world into independently ticking regions:",
      " * never use the global Bukkit scheduler; schedule work on the",
      " * entity/region scheduler that owns the data you touch.",
      " */",
      `public final class ${mainClass} extends JavaPlugin {`,
      "    @Override",
      "    public void onEnable() {",
      `        getLogger().info("${context.name} enabled (Folia)");`,
      "    }",
      "}",
      "",
    ].join("\n"),
  });

  files.push(...extraModuleSources(context, "plugin"));
  files.push(...renderExtraModuleBuilds(context));
  return files;
};
