import { packagePath, pascalCase, type PlatformRenderer, type TemplateFile } from "./types.js";

/**
 * Folia templates: like Paper but with the classic `plugin.yml`
 * (Folia does not support the paper-plugin bootstrap model) and
 * scheduling guidance for the regionised threaded server.
 */
export const renderFolia: PlatformRenderer = (context) => {
  const pkg = packagePath(context.packageName);
  const mainClass = pascalCase(context.name);
  const files: TemplateFile[] = [];

  files.push({
    path: "settings.gradle",
    contents: [
      "pluginManagement {",
      "    repositories {",
      "        gradlePluginPortal()",
      "    }",
      "}",
      "",
      `rootProject.name = '${context.name}'`,
      "",
    ].join("\n"),
  });

  files.push({
    path: "build.gradle",
    contents: [
      "plugins {",
      "    java",
      "}",
      "",
      `version = '${context.version}'`,
      `group = '${context.packageName}'`,
      "",
      "java.toolchain.languageVersion = JavaLanguageVersion.of(21)",
      "",
      "repositories {",
      "    mavenCentral()",
      "    maven { url = 'https://repo.papermc.io/repository/maven-public/' }",
      "}",
      "",
      "dependencies {",
      "    compileOnly 'dev.folia:folia-api:1.21.1-R0.1-SNAPSHOT'",
      "}",
      "",
      "tasks.withType(JavaCompile).configureEach {",
      "    it.options.encoding = 'UTF-8'",
      "    it.options.release = 21",
      "}",
      "",
    ].join("\n"),
  });

  files.push({
    path: "src/main/resources/plugin.yml",
    contents: [
      `name: ${context.name}`,
      `version: '${context.version}'`,
      "main: " + `${context.packageName}.${mainClass}`,
      "api-version: '1.21'",
      "description: Generated by Devix for Folia",
      "folia-supported: true",
      "",
    ].join("\n"),
  });

  files.push({
    path: `src/main/java/${pkg}/${mainClass}.java`,
    contents: [
      `package ${context.packageName};`,
      "",
      "import org.bukkit.plugin.java.JavaPlugin;",
      "",
      "/**",
      ` * Entry point of the ${context.name} plugin on Folia.`,
      " *",
      " * Folia splits the world into independently ticking regions:",
      " * never use the global Bukkit scheduler; schedule work on the",
      " * entity/region scheduler that owns the data you touch.",
      " */",
      `public final class ${mainClass} extends JavaPlugin {`,
      "    @Override",
      "    public void onEnable() {",
      `        getLogger().info("${context.name} enabled (Folia)");`,
      "    }",
      "}",
      "",
    ].join("\n"),
  });

  files.push({
    path: ".gitignore",
    contents: ["build/", ".gradle/", "run/", ""].join("\n"),
  });

  return files;
};
