import {
  extraModuleDependencies,
  gradleJavaBlocks,
  moduleResources,
  moduleSrcMain,
  renderSingleModuleSettings,
} from "./gradle-common.js";
import {
  gradleGitignore,
  renderExtraModuleBuilds,
  renderMultimoduleSettings,
} from "./gradle-multimodule.js";
import {
  extraModules,
  packagePath,
  pascalCase,
  type PlatformRenderer,
  type TemplateContext,
  type TemplateFile,
} from "./types.js";

/** Extra module starter sources shared by Paper/Folia/Velocity. */
export function extraModuleSources(context: TemplateContext, kindLabel: string): TemplateFile[] {
  const mainClass = pascalCase(context.name);
  return extraModules(context).map((module) => {
    const modulePackage = `${context.packageName}.${module.replace(/-/g, "")}`;
    const moduleClass = module === "api" ? `${mainClass}Api` : `${mainClass}${pascalCase(module)}`;
    return {
      path: `${moduleSrcMain(module, false)}/${packagePath(modulePackage)}/${moduleClass}.java`,
      contents:
        module === "api"
          ? [
              `package ${modulePackage};`,
              "",
              "/**",
              ` * Public API of the ${context.name} ${kindLabel}.`,
              " */",
              `public interface ${moduleClass} {`,
              "}",
              "",
            ].join("\n")
          : [
              `package ${modulePackage};`,
              "",
              "/**",
              ` * ${pascalCase(module)} module of the ${context.name} ${kindLabel}.`,
              " */",
              `public final class ${moduleClass} {`,
              `    private ${moduleClass}() {}`,
              "}",
              "",
            ].join("\n"),
    };
  });
}

/**
 * Paper templates: Gradle build against `paper-api` (version catalog),
 * `paper-plugin.yml` with bootstrap + loader, and multi-module
 * support via extra Gradle subprojects.
 */
export const renderPaper: PlatformRenderer = (context) => {
  const deps = context.versions[0]?.deps ?? {};
  const mainClass = pascalCase(context.name);
  const pkg = packagePath(context.packageName);
  const files: TemplateFile[] = [];

  files.push({
    path: "settings.gradle",
    contents: context.multimodule
      ? renderMultimoduleSettings(context)
      : renderSingleModuleSettings(context.name, ["gradlePluginPortal()"]),
  });

  files.push({
    path: "build.gradle",
    contents: [
      "plugins {",
      "    java",
      "}",
      "",
      `version = '${context.version}'`,
      `group = '${context.packageName}'`,
      "",
      "repositories {",
      "    mavenCentral()",
      "    maven { url = 'https://repo.papermc.io/repository/maven-public/' }",
      "}",
      "",
      "dependencies {",
      '    compileOnly "io.papermc.paper:paper-api:${project.api_version}"',
      ...extraModuleDependencies(context),
      "}",
      "",
      ...gradleJavaBlocks(context.versions[0]?.javaVersion ?? 21),
    ].join("\n"),
  });

  files.push({
    path: "gradle.properties",
    contents: [
      "org.gradle.jvmargs=-Xmx2G",
      "",
      "# Version catalog (managed by devix minecraft init --mc)",
      ...Object.entries(deps).map(([key, value]) => `${key}=${value}`),
      "",
    ].join("\n"),
  });

  files.push({
    path: `${moduleResources(context.modules[0] ?? "main", true)}/paper-plugin.yml`,
    contents: [
      `name: ${context.name}`,
      `version: '${context.version}'`,
      `main: ${context.packageName}.${mainClass}`,
      `api-version: '${context.versions[0]?.minecraft ?? "1.21"}'`,
      "description: Generated by Devix",
      `bootstrapper: ${context.packageName}.${mainClass}Bootstrap`,
      `loader: ${context.packageName}.${mainClass}Loader`,
      "",
    ].join("\n"),
  });

  files.push({
    path: `${moduleSrcMain(context.modules[0] ?? "main", true)}/${pkg}/${mainClass}Loader.java`,
    contents: [
      `package ${context.packageName};`,
      "",
      "import io.papermc.paper.plugin.loader.PluginClasspathBuilder;",
      "import io.papermc.paper.plugin.loader.PluginLoader;",
      "",
      "/** Class loader hook required by paper-plugin.yml. */",
      `public final class ${mainClass}Loader implements PluginLoader {`,
      "    @Override",
      "    public void classloader(PluginClasspathBuilder classpathBuilder) {",
      "        // Register extra libraries here when you need them.",
      "    }",
      "}",
      "",
    ].join("\n"),
  });

  files.push({
    path: `${moduleSrcMain(context.modules[0] ?? "main", true)}/${pkg}/${mainClass}Bootstrap.java`,
    contents: [
      `package ${context.packageName};`,
      "",
      "import io.papermc.paper.plugin.bootstrap.PluginBootstrap;",
      "import io.papermc.paper.plugin.bootstrap.PluginProviderContext;",
      "import org.bukkit.plugin.java.JavaPlugin;",
      "",
      "/** Bootstrap hook required by paper-plugin.yml. */",
      `public final class ${mainClass}Bootstrap implements PluginBootstrap {`,
      "    @Override",
      "    public void bootstrap(PluginProviderContext context) {",
      `        context.getLogger().info("${context.name} bootstrapping");`,
      "    }",
      "",
      "    @Override",
      "    public JavaPlugin createPlugin(PluginProviderContext context) {",
      `        return new ${mainClass}();`,
      "    }",
      "}",
      "",
    ].join("\n"),
  });

  files.push({
    path: `${moduleSrcMain(context.modules[0] ?? "main", true)}/${pkg}/${mainClass}.java`,
    contents: [
      `package ${context.packageName};`,
      "",
      "import org.bukkit.plugin.java.JavaPlugin;",
      "",
      "/**",
      ` * Entry point of the ${context.name} plugin.`,
      " */",
      `public final class ${mainClass} extends JavaPlugin {`,
      "    @Override",
      "    public void onEnable() {",
      `        getLogger().info("${context.name} enabled");`,
      "    }",
      "}",
      "",
    ].join("\n"),
  });

  files.push(...extraModuleSources(context, "plugin"));
  files.push(...renderExtraModuleBuilds(context));
  files.push({ path: ".gitignore", contents: gradleGitignore() });
  return files;
};
