import { packagePath, pascalCase, type PlatformRenderer, type TemplateFile } from "./types.js";

/**
 * Paper templates: Gradle with the paperweight-userdev-free paper-api
 * dependency, `paper-plugin.yml` and the JavaPlugin main class.
 */
export const renderPaper: PlatformRenderer = (context) => {
  const pkg = packagePath(context.packageName);
  const mainClass = pascalCase(context.name);
  const files: TemplateFile[] = [];

  files.push({
    path: "settings.gradle",
    contents: [
      "pluginManagement {",
      "    repositories {",
      "        gradlePluginPortal()",
      "    }",
      "}",
      "",
      `rootProject.name = '${context.name}'`,
      "",
    ].join("\n"),
  });

  files.push({
    path: "build.gradle",
    contents: [
      "plugins {",
      "    java",
      "}",
      "",
      `version = '${context.version}'`,
      `group = '${context.packageName}'`,
      "",
      "java.toolchain.languageVersion = JavaLanguageVersion.of(21)",
      "",
      "repositories {",
      "    mavenCentral()",
      "    maven { url = 'https://repo.papermc.io/repository/maven-public/' }",
      "}",
      "",
      "dependencies {",
      "    compileOnly 'io.papermc.paper:paper-api:1.21.1-R0.1-SNAPSHOT'",
      "}",
      "",
      "tasks.withType(JavaCompile).configureEach {",
      "    it.options.encoding = 'UTF-8'",
      "    it.options.release = 21",
      "}",
      "",
    ].join("\n"),
  });

  files.push({
    path: "src/main/resources/paper-plugin.yml",
    contents: [
      `name: ${context.name}`,
      `version: '${context.version}'`,
      "main: " + `${context.packageName}.${mainClass}`,
      "api-version: '1.21'",
      "description: Generated by Devix",
      "bootstrapper: " + `${context.packageName}.${mainClass}Bootstrap`,
      "loader: " + `${context.packageName}.${mainClass}Loader`,
      "",
    ].join("\n"),
  });

  files.push({
    path: `src/main/java/${pkg}/${mainClass}Loader.java`,
    contents: [
      `package ${context.packageName};`,
      "",
      "import io.papermc.paper.plugin.loader.PluginClasspathBuilder;",
      "import io.papermc.paper.plugin.loader.PluginLoader;",
      "",
      "/** Class loader hook required by paper-plugin.yml. */",
      `public final class ${mainClass}Loader implements PluginLoader {`,
      "    @Override",
      "    public void classloader(PluginClasspathBuilder classpathBuilder) {",
      "        // Register extra libraries here when you need them.",
      "    }",
      "}",
      "",
    ].join("\n"),
  });

  files.push({
    path: `src/main/java/${pkg}/${mainClass}Bootstrap.java`,
    contents: [
      `package ${context.packageName};`,
      "",
      "import io.papermc.paper.plugin.bootstrap.PluginBootstrap;",
      "import io.papermc.paper.plugin.bootstrap.PluginProviderContext;",
      "import org.bukkit.plugin.java.JavaPlugin;",
      "",
      "/** Bootstrap hook required by paper-plugin.yml. */",
      `public final class ${mainClass}Bootstrap implements PluginBootstrap {`,
      "    @Override",
      "    public void bootstrap(PluginProviderContext context) {",
      `        context.getLogger().info("${context.name} bootstrapping");`,
      "    }",
      "",
      "    @Override",
      "    public JavaPlugin createPlugin(PluginProviderContext context) {",
      `        return new ${mainClass}();`,
      "    }",
      "}",
      "",
    ].join("\n"),
  });

  files.push({
    path: `src/main/java/${pkg}/${mainClass}.java`,
    contents: [
      `package ${context.packageName};`,
      "",
      "import org.bukkit.plugin.java.JavaPlugin;",
      "",
      "/**",
      ` * Entry point of the ${context.name} plugin.`,
      " */",
      `public final class ${mainClass} extends JavaPlugin {`,
      "    @Override",
      "    public void onEnable() {",
      `        getLogger().info("${context.name} enabled");`,
      "    }",
      "}",
      "",
    ].join("\n"),
  });

  files.push({
    path: ".gitignore",
    contents: ["build/", ".gradle/", "run/", ""].join("\n"),
  });

  return files;
};
