import { moduleResources, moduleSrcMain } from "./gradle-common.js";
import {
  mavenGitignore,
  renderMavenExtraModulePoms,
  renderMavenModulePom,
  renderMavenParentPom,
  renderStandaloneMavenPom,
} from "./maven-multimodule.js";
import {
  extraModules,
  packagePath,
  pascalCase,
  type PlatformRenderer,
  type TemplateContext,
  type TemplateFile,
} from "./types.js";
import { extraModuleSources } from "./paper.js";

/** The spigot-api dependency XML of the version catalog line. */
function spigotDependency(context: TemplateContext): string[] {
  const deps = context.versions[0]?.deps ?? {};
  return [
    "        <dependency>",
    "            <groupId>org.spigotmc</groupId>",
    "            <artifactId>spigot-api</artifactId>",
    `            <version>${deps.api_version ?? "1.21.1-R0.1-SNAPSHOT"}</version>`,
    "            <scope>provided</scope>",
    "        </dependency>",
  ];
}

/**
 * Spigot/Bukkit templates: Maven against `spigot-api`, `plugin.yml`
 * and the `JavaPlugin` main class; with extra modules the project
 * becomes a Maven reactor (parent pom + one pom per module).
 */
export const renderSpigot: PlatformRenderer = (context) => {
  const mainClass = pascalCase(context.name);
  const pkg = packagePath(context.packageName);
  const slug = packagePath(context.packageName).split("/").pop() ?? "project";
  const files: TemplateFile[] = [];

  if (context.multimodule) {
    // The parent aggregator lives in pom-parent.xml; the entrypoint
    // module keeps the canonical pom.xml (with the parent block) so a
    // plain `mvn package` at the root still builds the plugin jar.
    files.push({
      path: "pom.xml",
      contents: renderMavenModulePom(context, slug, context.modules[0] ?? "main", true),
    });
    files.push({
      path: "pom-parent.xml",
      contents: renderMavenParentPom(context, slug),
    });
    for (const module of extraModules(context)) {
      files.push({
        path: `${module}/pom.xml`,
        contents: renderMavenModulePom(context, slug, module, false),
      });
    }
  } else {
    files.push({
      path: "pom.xml",
      contents: renderStandaloneMavenPom(context, slug, spigotDependency(context), [
        "        <repository>",
        "            <id>spigotmc-repo</id>",
        "            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>",
        "        </repository>",
      ]),
    });
  }

  files.push({
    path: `${moduleResources(context.modules[0] ?? "main", true)}/plugin.yml`,
    contents: [
      `name: ${context.name}`,
      `version: '${context.version}'`,
      `main: ${context.packageName}.${mainClass}`,
      `api-version: '${context.versions[0]?.minecraft ?? "1.21"}'`,
      "description: Generated by Devix",
      "",
    ].join("\n"),
  });

  files.push({
    path: `${moduleSrcMain(context.modules[0] ?? "main", true)}/${pkg}/${mainClass}.java`,
    contents: [
      `package ${context.packageName};`,
      "",
      "import org.bukkit.plugin.java.JavaPlugin;",
      "",
      "/**",
      ` * Entry point of the ${context.name} plugin.`,
      " */",
      `public final class ${mainClass} extends JavaPlugin {`,
      "    @Override",
      "    public void onEnable() {",
      `        getLogger().info("${context.name} enabled");`,
      "    }",
      "",
      "    @Override",
      "    public void onDisable() {",
      `        getLogger().info("${context.name} disabled");`,
      "    }",
      "}",
      "",
    ].join("\n"),
  });

  files.push(...extraModuleSources(context, "plugin"));
  files.push(...renderMavenExtraModulePoms(context, slug));
  files.push({ path: ".gitignore", contents: mavenGitignore() });
  return files;
};
