import { packagePath, pascalCase, type PlatformRenderer, type TemplateFile } from "./types.js";

/**
 * Spigot/Bukkit templates: Maven pom against the spigot-api, a
 * `plugin.yml` and the JavaPlugin main class.
 */
export const renderSpigot: PlatformRenderer = (context) => {
  const pkg = packagePath(context.packageName);
  const mainClass = pascalCase(context.name);
  const files: TemplateFile[] = [];

  files.push({
    path: "pom.xml",
    contents: [
      '<?xml version="1.0" encoding="UTF-8"?>',
      '<project xmlns="http://maven.apache.org/POM/4.0.0"',
      '         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"',
      '         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">',
      "    <modelVersion>4.0.0</modelVersion>",
      "",
      `    <groupId>${context.packageName}</groupId>`,
      `    <artifactId>${context.name}</artifactId>`,
      `    <version>${context.version}</version>`,
      "    <packaging>jar</packaging>",
      "",
      "    <properties>",
      "        <maven.compiler.release>21</maven.compiler.release>",
      "        <project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>",
      "    </properties>",
      "",
      "    <repositories>",
      "        <repository>",
      "            <id>spigotmc-repo</id>",
      "            <url>https://hub.spigotmc.org/nexus/content/repositories/snapshots/</url>",
      "        </repository>",
      "    </repositories>",
      "",
      "    <dependencies>",
      "        <dependency>",
      "            <groupId>org.spigotmc</groupId>",
      "            <artifactId>spigot-api</artifactId>",
      "            <version>1.21.1-R0.1-SNAPSHOT</version>",
      "            <scope>provided</scope>",
      "        </dependency>",
      "    </dependencies>",
      "",
      "    <build>",
      "        <resources>",
      "            <resource>",
      "                <directory>src/main/resources</directory>",
      "                <filtering>true</filtering>",
      "            </resource>",
      "        </resources>",
      "    </build>",
      "</project>",
      "",
    ].join("\n"),
  });

  files.push({
    path: "src/main/resources/plugin.yml",
    contents: [
      `name: ${context.name}`,
      `version: '${context.version}'`,
      "main: " + `${context.packageName}.${mainClass}`,
      "api-version: '1.21'",
      "description: Generated by Devix",
      "",
    ].join("\n"),
  });

  files.push({
    path: `src/main/java/${pkg}/${mainClass}.java`,
    contents: [
      `package ${context.packageName};`,
      "",
      "import org.bukkit.plugin.java.JavaPlugin;",
      "",
      "/**",
      ` * Entry point of the ${context.name} plugin.`,
      " */",
      `public final class ${mainClass} extends JavaPlugin {`,
      "    @Override",
      "    public void onEnable() {",
      `        getLogger().info("${context.name} enabled");`,
      "    }",
      "",
      "    @Override",
      "    public void onDisable() {",
      `        getLogger().info("${context.name} disabled");`,
      "    }",
      "}",
      "",
    ].join("\n"),
  });

  files.push({
    path: ".gitignore",
    contents: ["target/", ".idea/", "*.iml", ""].join("\n"),
  });

  return files;
};
