import {
  extraModuleDependencies,
  gradleJavaBlocks,
  moduleSrcMain,
  renderSingleModuleSettings,
} from "./gradle-common.js";
import { renderExtraModuleBuilds, renderMultimoduleSettings } from "./gradle-multimodule.js";
import { packageLeaf, packagePath, pascalCase, type PlatformRenderer } from "./types.js";
import { extraModuleSources } from "./paper.js";

/**
 * Velocity templates: Gradle against `velocity-api` (version catalog),
 * an annotation-based plugin class whose annotation processor writes
 * `velocity-plugin.json`, and multi-module support.
 */
export const renderVelocity: PlatformRenderer = (context) => {
  const deps = context.versions[0]?.deps ?? {};
  const mainClass = pascalCase(context.name);
  const pkg = packagePath(context.packageName);
  const leaf = packageLeaf(context.packageName);
  const entryDir = moduleSrcMain(context.modules[0] ?? "main", true);

  return [
    {
      path: "settings.gradle",
      contents: context.multimodule
        ? renderMultimoduleSettings(context)
        : renderSingleModuleSettings(context.name, ["gradlePluginPortal()"]),
    },
    {
      path: "build.gradle",
      contents: [
        "plugins {",
        "    java",
        "    id 'com.gradleup.shadow' version '8.3.5'",
        "}",
        "",
        `version = '${context.version}'`,
        `group = '${context.packageName}'`,
        "",
        "repositories {",
        "    mavenCentral()",
        "    maven { url = 'https://repo.papermc.io/repository/maven-public/' }",
        "}",
        "",
        "dependencies {",
        '    compileOnly "com.velocitypowered:velocity-api:${project.api_version}"',
        '    annotationProcessor "com.velocitypowered:velocity-api:${project.api_version}"',
        ...extraModuleDependencies(context),
        "}",
        "",
        ...gradleJavaBlocks(context.versions[0]?.javaVersion ?? 21),
      ].join("\n"),
    },
    {
      path: "gradle.properties",
      contents: [
        "org.gradle.jvmargs=-Xmx2G",
        "",
        "# Version catalog (managed by devix minecraft init --mc)",
        ...Object.entries(deps).map(([key, value]) => `${key}=${value}`),
        "",
      ].join("\n"),
    },
    {
      path: `${entryDir}/${pkg}/${mainClass}.java`,
      contents: [
        `package ${context.packageName};`,
        "",
        "import com.google.inject.Inject;",
        "import com.velocitypowered.api.plugin.Plugin;",
        "import com.velocitypowered.api.plugin.annotation.DataDirectory;",
        "import com.velocitypowered.api.proxy.ProxyServer;",
        "import org.slf4j.Logger;",
        "",
        "import java.nio.file.Path;",
        "",
        "/**",
        ` * Entry point of the ${context.name} proxy plugin.`,
        " * The annotation processor writes velocity-plugin.json from this class.",
        " */",
        "@Plugin(",
        `    id = "${leaf}",`,
        `    name = "${context.name}",`,
        `    version = "${context.version}",`,
        '    description = "Generated by Devix"',
        ")",
        `public final class ${mainClass} {`,
        "    @Inject",
        `    public ${mainClass}(ProxyServer proxy, Logger logger, @DataDirectory Path dataDirectory) {`,
        `        logger.info("${context.name} loaded");`,
        "    }",
        "}",
        "",
      ].join("\n"),
    },
    ...extraModuleSources(context, "proxy plugin"),
    ...renderExtraModuleBuilds(context),
  ];
};
