import {
  packageLeaf,
  packagePath,
  pascalCase,
  type PlatformRenderer,
  type TemplateFile,
} from "./types.js";

/**
 * Velocity templates: Gradle against velocity-api, an annotation-based
 * plugin class and the `velocity-plugin.json` descriptor generated by
 * the annotation processor.
 */
export const renderVelocity: PlatformRenderer = (context) => {
  const pkg = packagePath(context.packageName);
  const mainClass = pascalCase(context.name);
  const leaf = packageLeaf(context.packageName);
  const files: TemplateFile[] = [];

  files.push({
    path: "settings.gradle",
    contents: [
      "pluginManagement {",
      "    repositories {",
      "        gradlePluginPortal()",
      "    }",
      "}",
      "",
      `rootProject.name = '${context.name}'`,
      "",
    ].join("\n"),
  });

  files.push({
    path: "build.gradle",
    contents: [
      "plugins {",
      "    java",
      "    id 'com.gradleup.shadow' version '8.3.5'",
      "}",
      "",
      `version = '${context.version}'`,
      `group = '${context.packageName}'`,
      "",
      "java.toolchain.languageVersion = JavaLanguageVersion.of(21)",
      "",
      "repositories {",
      "    mavenCentral()",
      "    maven { url = 'https://repo.papermc.io/repository/maven-public/' }",
      "}",
      "",
      "dependencies {",
      "    compileOnly 'com.velocitypowered:velocity-api:3.4.0-SNAPSHOT'",
      "    annotationProcessor 'com.velocitypowered:velocity-api:3.4.0-SNAPSHOT'",
      "}",
      "",
      "tasks.withType(JavaCompile).configureEach {",
      "    it.options.encoding = 'UTF-8'",
      "    it.options.release = 21",
      "}",
      "",
    ].join("\n"),
  });

  files.push({
    path: `src/main/java/${pkg}/${mainClass}.java`,
    contents: [
      `package ${context.packageName};`,
      "",
      "import com.google.inject.Inject;",
      "import com.velocitypowered.api.plugin.Plugin;",
      "import com.velocitypowered.api.plugin.annotation.DataDirectory;",
      "import com.velocitypowered.api.proxy.ProxyServer;",
      "import org.slf4j.Logger;",
      "",
      "import java.nio.file.Path;",
      "",
      "/**",
      ` * Entry point of the ${context.name} proxy plugin.`,
      " * The annotation processor writes velocity-plugin.json from this class.",
      " */",
      `@Plugin(`,
      `    id = "${leaf}",`,
      `    name = "${context.name}",`,
      `    version = "${context.version}",`,
      '    description = "Generated by Devix"',
      ")",
      `public final class ${mainClass} {`,
      "    @Inject",
      `    public ${mainClass}(ProxyServer proxy, Logger logger, @DataDirectory Path dataDirectory) {`,
      `        logger.info("${context.name} loaded");`,
      "    }",
      "}",
      "",
    ].join("\n"),
  });

  files.push({
    path: ".gitignore",
    contents: ["build/", ".gradle/", "run/", ""].join("\n"),
  });

  return files;
};
